modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
    modId = "tome_of_wonders"
    version = "${file.jarVersion}"
    logoFile = "tome_of_wonders.png"
    authors = ".magmastrider., -Ghoul-, platypushasnohat"
    displayName = "Tome Of Wonders"
    description = '''Wonderful mobs'''

[[dependencies.tome_of_wonders]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.tome_of_wonders]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"